[metadata]
description = PyTorch Extension Library of Optimized Graph Neural Network Algorithms
author = Your Name
author_email = your.email@example.com
keywords = pytorch, geometric-deep-learning, graph-neural-networks
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Development Status :: 5 - Production/Stable
    Intended Audience :: Developers
    Programming Language :: C++
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12

[options]
packages = ops_gnn
package_dir =
    =python
install_requires =
    torch>=1.8

[options.extras_require]
test =
    pytest
    pytest-cov

[aliases]
test = pytest
